language: python

python:
  - "2.7"

cache: apt

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-gi python-gobject python-gobject-dev python-gobject-2 python-paramiko gir1.2-gtk-3.0
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: python -m unittest tests
