language: python

python:
  - "2.7"

cache:
  - apt

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gir1.2-gtk-3.0 gir1.2-vte-2.90 python-cairo python-gi python-gi-cairo python-gobject python-gobject-2 python-gobject-dev python-paramiko
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - pip install pylint sphinx==1.2.2
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -r requirements.txt; fi
  - wget http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz
  - gunzip -f GeoLite2-City.mmdb.gz

script:
  - pylint --rcfile data/pylintrc king_phisher
  - python -m unittest -v tests
  - sphinx-build -v docs/source docs/html

notifications:
  irc:
    channels:
      - "chat.freenode.net#king-phisher"
    on_success: change
    on_failure: always
