language: python

python:
  - "2.7"

cache:
  - apt

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gir1.2-gtk-3.0 gir1.2-vte-2.90 gir1.2-webkit-3.0 python-cairo python-gi python-gi-cairo python-gobject python-gobject-2 python-gobject-dev python-paramiko python-tk
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - pip install sphinx
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -r requirements.txt; fi

script:
  - python -m unittest -v tests
  - sphinx-build docs/source docs/html
